### ISSUE TITLE
请问有获得cloth parse数据集的相关模型吗

### ISSUE THREAD

**Issue by all1new** [xiezhy6/GP-VTON#10]
请问有获得cloth parse数据集的相关模型吗😁 想试一下其他衣服

**Comment by xiezhy6** [comment]
> 请问有获得cloth parse数据集的相关模型吗😁 想试一下其他衣服

你好，cloth parse的数据集由于是公司内部模型，暂时不打算开源

**Comment by Gzzgz** [comment]
请问cloth parse的类别有多少？具体对应的语义是啥样的

**Comment by MahmoodMsarwa** [comment]
如何获取“bytedance”解析器。 ？
