### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by tobias861222** [xiezhy6/GP-VTON#11]
Hello everyone,

I'm currently working on implementing test inference on Windows using Anaconda. However, I'm encountering an issue with the slash in the paths. When I run the code, it causes problems due to the path format differences between Windows and Linux.

```
python3 -m torch.distributed.launch --master_port=4739 test_warping.py \ 
   --name test_partflow_vitonhd_unpaired_1109 \
   --PBAFN_warp_checkpoint 'checkpoints/gp-vton_partflow_vitonhd_usepreservemask_lrarms_1027/PBAFN_warp_epoch_121.pth' \
   --resize_or_crop None --verbose --tf_log \
   --batchSize 2 --label_nc 14 --launcher pytorch \
   --dataroot D:/Master/Virtual-try-on/2023/GP_VTON/dataset/VITON-HD \
   --image_pairs_txt test_pairs_unpaired_1018.txt \

```

`   
  File "D:\Master\Virtual-try-on\2023\GP_VTON\data\aligned_dataset_vitonhd.py", line 28, in initialize
    with open(pair_txt_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Master/Virtual-try-on/2023/GP-VTON/dataset/VITON-HD\\test_pairs_unpaired_1018.txt'`

How should I modify it to run successfully, thanks!

**Comment by Deepak2405** [comment]
you have to download all the necessary files and folders as mentioned in the read-me.

**Comment by tobias861222** [comment]
@Deepak2405 Thank you for your reply
I've already downloaded all the necessary files.
![image](https://github.com/xiezhy6/GP-VTON/assets/96098258/e75155cc-d4c8-4eda-aa16-775b18ad1407)
![image](https://github.com/xiezhy6/GP-VTON/assets/96098258/170749ce-0826-44e0-ab9b-6b4c206608ec)
I think the issue is still related to the file path. I have tried modifying aligned_dataset_vitonhd.py
`self.root = opt.dataroot`
I changed it to an absolute path.
`self.root = "D:/Master/Virtual-try-on/2023/GP_VTON/dataset/VITON-HD"`, 
and it allowed the execution to continue. However, there may still be other file path issues related to forward slashes () or backslashes (/).
`  File "test_warping.py", line 75, in <module>
    for ii, data in enumerate(tqdm.tqdm(train_loader)):
  File "C:\Users\Tobias\anaconda3\envs\gp_vton\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\Tobias\anaconda3\envs\gp_vton\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\Tobias\anaconda3\envs\gp_vton\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\Users\Tobias\anaconda3\envs\gp_vton\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Users\Tobias\anaconda3\envs\gp_vton\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Tobias\anaconda3\envs\gp_vton\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Tobias\anaconda3\envs\gp_vton\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Tobias\anaconda3\envs\gp_vton\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Master\Virtual-try-on\2023\GP_VTON\data\aligned_dataset_vitonhd.py", line 163, in __getitem__
    with open(pose_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Master/Virtual-try-on/2023/GP_VTON/dataset/VITON-HD\\test\\image\\05006_00_keypoints.json'`

**Comment by nazapip** [comment]
@Deepak2405 can you please help with the code for getting the inference results to see it on the real images please. I have been trying to run the test scripts and its running but how to proceed further to see the results on the images

**Comment by tobias861222** [comment]
Hello, everyone,
I modified the path to the following format, 
`
python test_warping.py \
    --name test_partflow_vitonhd_unpaired_1109 \
    --PBAFN_warp_checkpoint './checkpoints/gp-vton_partflow_vitonhd_usepreservemask_lrarms_1027/PBAFN_warp_epoch_121.pth' \
    --resize_or_crop None --verbose --tf_log \
    --batchSize 2 --label_nc 14 --launcher pytorch \
    --image_pairs_txt test_pairs_unpaired_1018.txt \
	--dataroot "./dataset/VITON-HD" \
	--gpu_ids 0 \
`
and now it can be executed. Thank you to everyone who replied.

**Comment by sudip550** [comment]
> Hello, everyone, I modified the path to the following format,
> 
> ```
> python test_warping.py \
>     --name test_partflow_vitonhd_unpaired_1109 \
>     --PBAFN_warp_checkpoint './checkpoints/gp-vton_partflow_vitonhd_usepreservemask_lrarms_1027/PBAFN_warp_epoch_121.pth' \
>     --resize_or_crop None --verbose --tf_log \
>     --batchSize 2 --label_nc 14 --launcher pytorch \
>     --image_pairs_txt test_pairs_unpaired_1018.txt \
> 	--dataroot "./dataset/VITON-HD" \
> 	--gpu_ids 0 \
> ```
> 
> and now it can be executed. Thank you to everyone who replied.

Can you please provide model files...
