### ISSUE TITLE
bad result

### ISSUE THREAD

**Issue by cskyy** [xiezhy6/GP-VTON#21]
Hello, the test using the pre-training model got bad results, why?
![屏幕截图 2023-07-01 153349](https://github.com/xiezhy6/GP-VTON/assets/108797152/00d6141d-e7c7-449f-bd5c-cf15cba6dd67)

**Comment by Nedae** [comment]
Did you get your answer? @cskyy

**Comment by cskyy** [comment]
I found the answer in the closed question 'Noise in the output', which is related to the size of batch_size. At first, the batch_size in the stage of synthetic fitting results was set to 1, and later it was changed to 4, and the result was completely different. Specific reasons were not mentioned in the answer to the previous question. I'm not sure why.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiezhy6/GP-VTON"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 凌晨3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiezhy6/GP-VTON] bad result (Issue #21)





 
Did you get your answer? @cskyy
