### ISSUE TITLE
How to get Clothe Parse? 我想知道如何获取新图像的 Clothe Parse？

### ISSUE THREAD

**Issue by generateRandomId** [xiezhy6/GP-VTON#23]
Hello! 
I wonder how to get Clothe Parse for new image? anyone give an advice on this???
Thank you for your attention.

你好！
我想知道如何获取新图像的 Clothe Parse？有人对此提出建议吗？
感谢您的关注。

**Comment by liupengcnu** [comment]
请问楼主解决了该问题吗？同样想知道如何获取新图像的cloth_parse

**Comment by generateRandomId** [comment]
抱歉，我找不到答案，所以我要关闭这个问题
