### ISSUE TITLE
Noise in the output

### ISSUE THREAD

**Issue by Deepak2405** [xiezhy6/GP-VTON#7]
Thank you for the wonderful work. When I am trying to reproduce the results, the warping part is excellent. However, there are lot of noisy-pixels in the final generated output. What could be the reason? Is there anyway I can modify to improve the output?

![upper___00006_00 png___06396_00](https://github.com/xiezhy6/GP-VTON/assets/3178134/e2dc125d-ed7f-4586-97e5-9d14a7a35a01)
![upper___00013_00 png___07845_00](https://github.com/xiezhy6/GP-VTON/assets/3178134/6eeae7fa-d66b-42e8-a860-49bdbca78a76)
![upper___00055_00 png___11351_00](https://github.com/xiezhy6/GP-VTON/assets/3178134/677ce76d-5365-4511-b184-16910692f3dd)

**Comment by TruongScotl** [comment]
How many batch_size that you run on the second stage?

**Comment by Deepak2405** [comment]
Thanks, I modified the batch size and got better outputs.

**Comment by MNMaqsood** [comment]
Hey, thanks for the work.

@Deepak2405 what batch size did you try? I am also facing this same issue.

**Comment by Deepak2405** [comment]
@MNMaqsood I set the batchsize to 8.

**Comment by nazapip** [comment]
@Deepak2405. Nice work!!. What did you exactly do after running the test script to visualize the results? What coding you did to test the results on the real images

**Comment by bryanhpchiang** [comment]
running into the same issue. setting batch size to something higher like 64 didn't really help

**Comment by prashant-kumar-meesho** [comment]
@Deepak2405 Can you provide gdrive link for model checkpoints.

**Comment by sudip550** [comment]
> @Deepak2405 Can you provide gdrive link for model checkpoints.

hey do you got model files?? please share
