### ISSUE TITLE
Any advantages over StableDiffusion based try-on methods?

### ISSUE THREAD

**Issue by weizmann** [xiezhy6/GP-VTON#8]
R.T.

**Comment by weizmann** [comment]
I am sorry that this question may be offensive. 

But considering that the SD-based methods are already very popular in the tech community, I believe that researchers in this field must face this tough question.

Therefore, I am looking forward your reply sincerely.

Thank you so much.

**Comment by sjcotto** [comment]
can u provide a repo with SD-based try ons?

**Comment by akarshgopal** [comment]
https://github.com/miccunifi/ladi-vton This one is Latent-Diffusion based

**Comment by sjcotto** [comment]
no code in that repo?
